version: "3.7"
   
services:
  emacs:
    image: ghcr.io/nakkaya/emacsd:latest
    privileged: true
    security_opt:
      - seccomp:unconfined
    restart: always
    volumes:
      - home:/home/core
    ports:
      - "9090:9090"
    #environment:
      #- PASSWD=pass

volumes:
  home:
