export LC_ALL=C.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

export PROMPT_DIRTRIM=2

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

if [ -f ~/.ssh/config ];
then
    function _ssh_completion() {
        perl -ne 'print "$1 " if /^[Hh]ost (.+)$/' ~/.ssh/config
    }
    complete -W "$(_ssh_completion)" ssh
fi

if [ -f /etc/bash_completion.d/git-prompt ];
then
    source /etc/bash_completion.d/git-prompt
fi

if [ -f /storage/.bashrc ];
then
    source /storage/.bashrc
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    *-color|*-256color) color_prompt=yes;;
esac

if [ "$color_prompt" = yes ]; then
    PS1='\[\033[01;32m\]emacsd@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \$ '
else
    PS1='emacsd@\h:\w \$ '
fi
unset color_prompt

if [ -z ${INSIDE_EMACS+x} ];
then
    # If this is an xterm set the title
    case "$TERM" in
	xterm*|rxvt*)
	    PS1="\[\e]0;emacsd@\h\a\]$PS1"
	    ;;
	*)
	    ;;
    esac
fi

alias ls='ls --color=auto'
alias emacs='SSH_TTY=`tty` emacsclient -s /opt/emacsd/server/emacsd --tty'
