name: CI

on:
  push:
    branches: [ master ]
  # schedule:
  #   - cron: '00 00 * * 1'  # Run at 00:00 on Monday.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Free Up Space
        run: sudo rm -rf /usr/local/lib/android && sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Docker Hub Login
        run: docker login --username nakkaya --password '${{ secrets.DOCKER_PASSWORD }}'

      - name: Docker GHCR Login
        run: docker login ghcr.io -u nakkaya --password '${{ secrets.GHCR_PASSWORD }}'

      - name: Install Invoke
        run: pip install invoke

      - name: Build Image
        run: invoke build --push
