name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        build-cmd:
          - build-gpu
          - buildx-cpu

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Docker Hub Login
        run: docker login ghcr.io -u nakkaya --password '${{ secrets.DOCKER_PASSWORD }}'

      - name: Docker GHCR Login
        run: docker login ghcr.io -u nakkaya --password '${{ secrets.GHCR_PASSWORD }}'

      - name: Install Invoke
        run: pip install invoke

      - name: Build Image
        run: invoke ${{ matrix.build-cmd }}
