name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Docker GHCR Login
        run: docker login ghcr.io -u nakkaya --password '${{ secrets.GHCR_PASSWORD }}'

      - name: Install Invoke
        run: pip install invoke

  buildx_amd64_gpu:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: invoke buildx-amd64-gpu

  buildx_amd64_cpu:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: invoke buildx-amd64-cpu

  buildx_arm64_cpu:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: invoke buildx-arm64-cpu
